name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run tests
      run: |
        python -m unittest discover -s tests/ -p '*_test.py'
      
    - name: Deploy to server
      if: github.event_name == 'push'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh -i <(echo "$SSH_PRIVATE_KEY") user@host "cd /var/www/flask-app && git pull && systemctl restart flask-app.service"
